plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - COPYING.md
  - doc/coding_standards.md
  - doc/core_correction.md
  - doc/ghosts.md
  - doc/libxc_use.md
  - doc/program_overview.md
  - doc/pwscf_exc.md
  - doc/relativistic.md
  - doc/release_notes.md
  - doc/users_guide.md
